### PR TITLE
Database Hardening

### PR DESCRIPTION
**Pull request by kkaprolat**
This is just a first draft and entirely untested. I try to replicate what [mysql_secure_installation.sh](https://github.com/MariaDB/server/blob/5566cbadb03856aba9c236b131f544490cd2bee4/scripts/mysql_secure_installation.sh) does automatically instead of an interactive script.

Alternatively we could add the whole script and just answer "yes" to what we want (hard-code the relevant if-statements). This may be safer. The script is also licensed under GPL2 which should be compatible with AGPL.

In any case I'd wait for https://github.com/TheNoim/DarkflameServer/pull/3 in order to add these changes to the setup script.

### CODE REVIEW

**Comment by kkaprolat** [comment]
Actually, maybe the SQL statements could just be added to the list of migrations. This would make an additional script unnecessary.

**Comment by kkaprolat** [comment]
I've done the latter.

Furthermore I checked the list of tipps from the [ArchWiki](https://wiki.archlinux.org/title/MariaDB#Improve_initial_security) on other hardening steps:
- listening only on the loopback address may be unnecessary, since there is only one interface for the container, so there are no side-effects when listening on all interfaces (please correct me if I'm wrong, I'm unsure here)
- enabling access only via Unix sockets is presumably not supported by the server, but if it is, this can also be done in the migrations (currently commented out)

I'm now checking whether the migrations are applied and whether everything works.

**Comment by kkaprolat** [comment]
Some observations:
- As expected, one cannot log in as 'test'.
- A login as root from outside the container is also not possible, as other containers are not localhost.
- After allowing root (for my own sanity), I could verify that the test db and anonymous users are actually removed.
- When we run e.g. phpmyadmin as another docker container attached to the same network, port forwarding of that container is not necessary.

So I assume that the fixes worked and this should be good to go.

**Comment by TheNoim** [comment]
Until this point I didn't had time to actually try this pr. I hope I have time later today.

**Pull request merged**
